### ISSUE TITLE
Can't get this working properly

### ISSUE THREAD

**Issue by Astiolo** [suoto/hdl_checker_vscode#1] opened 2019-10-23 03:41 UTC
I've got HDL Checker and this extension for VSCode installed, with a config file that lists all the ones I require. But this addon only seems to be able to tell me about unused variables. 

It can't find sources for any entities even if they are in the config file and already opened and doesn't warn about any other syntax errors.

It does warn me when I'm looking at a file which isn't in the config file so I believe it's running but I'm wondering if there's a bug currently or if I've missed part of the setup process.

**Comment by Astiolo** [comment] 2019-10-23 04:35
Installing ghdl made things better. But I still have one issue where it says it can't find packages that I'm using. The first time I mouse over that's all it says, if I then mouse over again after a couple seconds it gives me a correct path but still says it can't find it right underneath.

I do also have Vivado installed is there a way I can specify weather to use ghdl or Vivado?

**Comment by suoto** [comment] 2019-10-23 09:43
Hovering over a dependency (a package, entity, etc) should reveal which path defines it, if any. Additional errors likely mean the file defining this dependency has an error, so that GHDL in this case can't compile the current file properly. (Same applies to the compilation sequence files shown when hovering over an entity or package)

Does the file shown when you hover over a dependency has any errors?

**Comment by Astiolo** [comment] 2019-10-24 00:11
Thank you, I did find some things that ghdl didn't like now it all appears to be working.

I'm still trying to test it with XVHDL though. I've added the path including the binary ("/opt/Xilinx/Vivado/2018.2/bin/"), removed the one containing ghdl and then cleared the cache and now I'm getting an error in the tmp/hdl_checker_stderr_...log file. (I can run xvhdl from the command line)

`Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/home/lindsay/.local/lib/python2.7/site-packages/pyls/_utils.py", line 33, in run
    return func(*args, **kwargs)
  File "/home/lindsay/.local/lib/python2.7/site-packages/hdl_checker/lsp.py", line 300, in lint
    diagnostics = set(self._getDiags(doc_uri, is_saved)) | self._global_diags
  File "/home/lindsay/.local/lib/python2.7/site-packages/hdl_checker/lsp.py", line 327, in _getDiags
    diags = self.checker.getMessagesByPath(path)
  File "/home/lindsay/.local/lib/python2.7/site-packages/hdl_checker/base_server.py", line 486, in getMessagesByPath
    builder_diags |= {x for x in builder_check.get()}
  File "/home/lindsay/.local/lib/python2.7/site-packages/hdl_checker/base_server.py", line 486, in <setcomp>
    builder_diags |= {x for x in builder_check.get()}
  File "/home/lindsay/.local/lib/python2.7/site-packages/hdl_checker/base_server.py", line 396, in _getBuilderMessages
    dep_path, dep_library, scope=BuildFlagScope.dependencies
  File "/home/lindsay/.local/lib/python2.7/site-packages/hdl_checker/base_server.py", line 422, in _buildAndHandleRebuilds
    path=path, library=library, scope=scope, forced=forced
  File "/home/lindsay/.local/lib/python2.7/site-packages/hdl_checker/builders/base_builder.py", line 429, in build
    path, library, self._getFlags(path, scope)
  File "/home/lindsay/.local/lib/python2.7/site-packages/hdl_checker/builders/base_builder.py", line 327, in _buildAndParse
    for _record in self._makeRecords(line):
  File "/home/lindsay/.local/lib/python2.7/site-packages/hdl_checker/builders/xvhdl.py", line 97, in _makeRecords
    line_number=int(info["line_number"]) - 1,
TypeError: int() argument must be a string or a number, not 'NoneType'`

**Comment by suoto** [comment] 2019-10-24 07:50
Ok, that's a bug when parsing XVHDL output, I'll have a look at that. If you can run it on the command line, would be helpful if you could paste XVHDL output!

Thanks for reporting :+1:

**Comment by suoto** [comment] 2019-10-25 12:08
Found the cause of the issue and fixed suoto/hdl_checker@6fddf2fe3f54be696376bc5faab43482a8d03d30.

If you want to try with the fix you can `pip install git+https://github.com/suoto/hdl_checker@master -U`

**Comment by suoto** [comment] 2019-10-27 15:37
Going to close this for now, if there's any issues let me know

**Closed by suoto** 2019-10-27 15:37 UTC
